// <auto-generated />
using System;
using CIDM3312Project.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CIDM3312Project.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20181206213704_migration")]
    partial class migration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846");

            modelBuilder.Entity("CIDM3312Project.Models.Client", b =>
                {
                    b.Property<int>("ClientID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("OrganizationName");

                    b.Property<string>("PhoneNumber");

                    b.HasKey("ClientID");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("CIDM3312Project.Models.Member", b =>
                {
                    b.Property<int>("MemberID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("Major");

                    b.Property<string>("PhoneNumber");

                    b.Property<int?>("ProjectDetailsClientID");

                    b.Property<int?>("ProjectDetailsProjectID");

                    b.HasKey("MemberID");

                    b.HasIndex("ProjectDetailsClientID", "ProjectDetailsProjectID");

                    b.ToTable("Member");
                });

            modelBuilder.Entity("CIDM3312Project.Models.Project", b =>
                {
                    b.Property<int>("ProjectID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Deadline");

                    b.Property<int>("EstimatedHours");

                    b.Property<string>("ProjectName");

                    b.HasKey("ProjectID");

                    b.ToTable("Project");
                });

            modelBuilder.Entity("CIDM3312Project.Models.ProjectDetails", b =>
                {
                    b.Property<int>("ClientID");

                    b.Property<int>("ProjectID");

                    b.HasKey("ClientID", "ProjectID");

                    b.HasIndex("ProjectID");

                    b.ToTable("ProjectDetails");
                });

            modelBuilder.Entity("CIDM3312Project.Models.Member", b =>
                {
                    b.HasOne("CIDM3312Project.Models.ProjectDetails")
                        .WithMany("Members")
                        .HasForeignKey("ProjectDetailsClientID", "ProjectDetailsProjectID");
                });

            modelBuilder.Entity("CIDM3312Project.Models.ProjectDetails", b =>
                {
                    b.HasOne("CIDM3312Project.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CIDM3312Project.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
